package it.meet.beans;
// Generated 21-set-2013 9.59.58 by Hibernate Tools 3.2.1.GA

import java.util.Date;

/**
 * FriendsRequests generated by hbm2java
 */
public class FriendsRequests implements java.io.Serializable {

    private FriendsRequestsId id;
    private Users sender;
    private Users receiver;
    private String message;
    private Date daterequest;
    private Boolean accepted;
    private String enddate;

    public FriendsRequests() {
    }

    public FriendsRequests(FriendsRequestsId id, Users sender, Users receiver, Date daterequest, String enddate) {
        this.id = id;
        this.sender = sender;
        this.receiver = receiver;
        this.daterequest = daterequest;
        this.enddate = enddate;
    }

    public FriendsRequests(FriendsRequestsId id, Users sender, Users receiver, String message, Date daterequest, String enddate, Boolean accepted) {
        this.id = id;
        this.sender = sender;
        this.receiver = receiver;
        this.message = message;
        this.daterequest = daterequest;
        this.accepted = accepted;
        this.enddate = enddate;
    }

    public FriendsRequestsId getId() {
        return this.id;
    }

    public void setId(FriendsRequestsId id) {
        this.id = id;
    }

    public Users getSender() {
        return this.sender;
    }

    public void setSender(Users sender) {
        this.sender = sender;
    }

    public Users getReceiver() {
        return this.receiver;
    }

    public void setReceiver(Users receiver) {
        this.receiver = receiver;
    }

    public String getMessage() {
        return this.message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    public Date getDaterequest() {
        return this.daterequest;
    }

    public void setDaterequest(Date daterequest) {
        this.daterequest = daterequest;
    }

    public Boolean getAccepted() {
        return this.accepted;
    }

    public void setAccepted(Boolean accepted) {
        this.accepted = accepted;
    }

    /**
     * @return the enddate
     */
    public String getEnddate() {
        return enddate;
    }

    /**
     * @param enddate the enddate to set
     */
    public void setEnddate(String enddate) {
        this.enddate = enddate;
    }
}
