package it.meet.beans;
// Generated 21-set-2013 9.59.58 by Hibernate Tools 3.2.1.GA

/**
 * Messages generated by hbm2java
 */
public class Messages implements java.io.Serializable {

    private MessagesId id;
    private Users sender;
    private Users receiver;
    private String state;
    private String message;

    public Messages() {
    }

    public Messages(MessagesId id, Users sender, Users receiver, String state, String message) {
        this.id = id;
        this.sender = sender;
        this.receiver = receiver;
        this.state = state;
        this.message = message;
    }

    public MessagesId getId() {
        return this.id;
    }

    public void setId(MessagesId id) {
        this.id = id;
    }

    public Users getSender() {
        return this.sender;
    }

    public void setSender(Users sender) {
        this.sender = sender;
    }

    public Users getReceiver() {
        return this.receiver;
    }

    public void setReceiver(Users receiver) {
        this.receiver = receiver;
    }

    public String getMessage() {
        return this.message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    /**
     * @return the state
     */
    public String getState() {
        return state;
    }

    /**
     * @param state the state to set
     */
    public void setState(String state) {
        this.state = state;
    }
}
