package it.meet.beans;

import java.util.Date;

/**
 * NotificationOffline generated by hbm2java
 */
public class NotificationOffline implements java.io.Serializable {

    private String username;
    private Users users;
    private String registrationId;
    private String lastMessage;
    private Date dateLastNotification;
    private String status;
    private String deviceType;

    public NotificationOffline() {
    }

    public NotificationOffline(String username, Users users, String registrationId) {
        this.username = username;
        this.users = users;
        this.registrationId = registrationId;
    }

    public NotificationOffline(String username, Users users, String registrationId, String lastMessage, Date dateLastNotification, String status, String deviceType) {
        this.username = username;
        this.users = users;
        this.registrationId = registrationId;
        this.lastMessage = lastMessage;
        this.dateLastNotification = dateLastNotification;
        this.status = status;
        this.deviceType = deviceType;
    }

    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public Users getUsers() {
        return this.users;
    }

    public void setUsers(Users users) {
        this.users = users;
    }

    public String getRegistrationId() {
        return registrationId;
    }

    public void setRegistrationId(String registrationId) {
        this.registrationId = registrationId;
    }

    public String getLastMessage() {
        return lastMessage;
    }

    public void setLastMessage(String lastMessage) {
        this.lastMessage = lastMessage;
    }

    public Date getDateLastNotification() {
        return dateLastNotification;
    }

    public void setDateLastNotification(Date dateLastNotification) {
        this.dateLastNotification = dateLastNotification;
    }

    public String getStatus() {
        return this.status;
    }

    public void setStatus(String state) {
        this.status = state;
    }

    public String getDeviceType() {
        return deviceType;
    }

    public void setDeviceType(String deviceType) {
        this.deviceType = deviceType;
    }
}
