package it.meet.beans;


import java.util.Date;

/**
 * NotificatonOffline generated by hbm2java
 */
public class NotificatonOffline  implements java.io.Serializable {


     private String username;
     private Users users;
     private String registrationid;
     private String lastmessage;
     private Date datelastnotificaton;
     private String state;

    public NotificatonOffline() {
    }

	
    public NotificatonOffline(String username, Users users, String registrationid) {
        this.username = username;
        this.users = users;
        this.registrationid = registrationid;
    }
    public NotificatonOffline(String username, Users users, String registrationid, String lastmessage, Date datelastnotificaton, String state) {
       this.username = username;
       this.users = users;
       this.registrationid = registrationid;
       this.lastmessage = lastmessage;
       this.datelastnotificaton = datelastnotificaton;
       this.state = state;
    }
   
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public String getRegistrationid() {
        return this.registrationid;
    }
    
    public void setRegistrationid(String registrationid) {
        this.registrationid = registrationid;
    }
    public String getLastmessage() {
        return this.lastmessage;
    }
    
    public void setLastmessage(String lastmessage) {
        this.lastmessage = lastmessage;
    }
    public Date getDatelastnotificaton() {
        return this.datelastnotificaton;
    }
    
    public void setDatelastnotificaton(Date datelastnotificaton) {
        this.datelastnotificaton = datelastnotificaton;
    }
    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }




}


