package it.meet.beans;
// Generated 21-set-2013 9.59.58 by Hibernate Tools 3.2.1.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Users generated by hbm2java
 */
public class Users implements java.io.Serializable {

    private String username;
    private String password;
    private String name;
    private String surname;
    private Character sex;
    private String email;
    private String enddate;
    private Date dateOfBirth;
    private String telephonenumber;
    private byte[] photo;
    private Set<Users> blackList = new HashSet<Users>(0);
    private Set<FriendsRequests> friendRequestSent = new HashSet<FriendsRequests>(0);
    private Set<Messages> messagesesReceived = new HashSet<Messages>(0);
    private Set<Messages> messagesesSent = new HashSet<Messages>(0);
    private Set<FriendsRequests> friendRequestReceived = new HashSet<FriendsRequests>(0);
    private Set<Users> friends = new HashSet<Users>(0);
    private NotificationOffline lastNotificationOffline;

    public Users() {
    }

    public Users(String username, String password, String enddate) {
        this.username = username;
        this.password = password;
        this.enddate = enddate;
    }

    public Users(String username, String password, String name, String surname, Character sex, String email, String enddate, Date dateOfBirth, String telephonenumber, byte[] photo, Set<Users> blackList, Set<FriendsRequests> friendRequestSent, Set<Messages> messagesesReceived, Set<Messages> messagesesSent, Set<FriendsRequests> friendRequestReceived, Set<Users> friends, NotificationOffline lastNotificationOffline) {
        this.username = username;
        this.password = password;
        this.name = name;
        this.surname = surname;
        this.sex = sex;
        this.email = email;
        this.enddate = enddate;
        this.dateOfBirth = dateOfBirth;
        this.telephonenumber = telephonenumber;
        this.photo = photo;
        this.blackList = blackList;
        this.friendRequestSent = friendRequestSent;
        this.messagesesReceived = messagesesReceived;
        this.messagesesSent = messagesesSent;
        this.friendRequestReceived = friendRequestReceived;
        this.friends = friends;
        this.lastNotificationOffline = lastNotificationOffline;
    }

    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getSurname() {
        return this.surname;
    }

    public void setSurname(String surname) {
        this.surname = surname;
    }

    public Character getSex() {
        return this.sex;
    }

    public void setSex(Character sex) {
        this.sex = sex;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getEnddate() {
        return this.enddate;
    }

    public void setEnddate(String enddate) {
        this.enddate = enddate;
    }

    public Date getDateOfBirth() {
        return dateOfBirth;
    }

    public void setDateOfBirth(Date dateOfBirth) {
        this.dateOfBirth = dateOfBirth;
    }

    public String getTelephonenumber() {
        return this.telephonenumber;
    }

    public void setTelephonenumber(String telephonenumber) {
        this.telephonenumber = telephonenumber;
    }

    public byte[] getPhoto() {
        return this.photo;
    }

    public void setPhoto(byte[] photo) {
        this.photo = photo;
    }

    public Set<Users> getBlackList() {
        return this.blackList;
    }

    public void setBlackList(Set<Users> blackList) {
        this.blackList = blackList;
    }

    public Set<FriendsRequests> getFriendRequestSent() {
        return this.friendRequestSent;
    }

    public void setFriendRequestSent(Set<FriendsRequests> friendRequestSent) {
        this.friendRequestSent = friendRequestSent;
    }

    public Set<Messages> getMessagesesReceived() {
        return this.messagesesReceived;
    }

    public void setMessagesesReceived(Set<Messages> messagesesReceived) {
        this.messagesesReceived = messagesesReceived;
    }

    public Set<Messages> getMessagesesSent() {
        return this.messagesesSent;
    }

    public void setMessagesesSent(Set<Messages> messagesesSent) {
        this.messagesesSent = messagesesSent;
    }

    public Set<FriendsRequests> getFriendRequestReceived() {
        return this.friendRequestReceived;
    }

    public void setFriendRequestReceived(Set<FriendsRequests> friendRequestReceived) {
        this.friendRequestReceived = friendRequestReceived;
    }

    public Set<Users> getFriends() {
        return this.friends;
    }

    public void setFriends(Set<Users> friends) {
        this.friends = friends;
    }

    /**
     * @return the lastNotificationOffline
     */
    public NotificationOffline getLastNotificationOffline() {
        return lastNotificationOffline;
    }

    /**
     * @param lastNotificationOffline the lastNotificationOffline to set
     */
    public void setLastNotificationOffline(NotificationOffline lastNotificationOffline) {
        this.lastNotificationOffline = lastNotificationOffline;
    }
}
